### ISSUE TITLE
Foreign Key e ait iliskisel nesneyi Almak

### ISSUE THREAD

**Issue by ahmetugur** [Medyasoft/unigate-public#10]
Haber Tablosundaki ForeignKey olan KategoriId e ait Kategori nesnesini almak istiyorum mümkün müdür? 
Bu şuan için yapılamaz ise en azından Page tablosundaki ParentPageId e baglı Page nesnesini alabilmeliyim.
Örnek; Page.SiteLanguage alınabiliyor

**Comment by esrefatak** [comment]
Bu çok büyük bir karar. Ürünün geleceğe dönük hedeflerine ters olduğu için issue'yu kapatıyoruz.
