### ISSUE TITLE
Silme işleminden sonra pencere tekrar geliyor, gelmesin

### ISSUE THREAD

**Issue by vunalan** [Medyasoft/unigate-public#100]
UniGate > Listelerim > Başlık   - Sil dediğimizde 1 ve 2. admlardan sonra 3. adımın gelmesi işi uzatmaktadır. 2. Adımda zaten sil diyoruz. 3'ün gelmemesi gerekli.

**Comment by esrefatak** [comment]
Silmek için onay soruyor bunu mu istemiyorsunuz?

**Comment by vunalan** [comment]
Silmek için Onay sorsun.
Onay sonrası içerik düzenleme penceresi tekrar açılıyor. Gereksiz kalıyor bu işlem.

**Comment by vunalan** [comment]
Üst mesajda foto olarak belirttim.

**Comment by esrefatak** [comment]
Başlığını düzelttim, bildirim için teşekkürler.
Road map'e alacağız.

**Comment by esrefatak** [comment]
Mükerrer olduğundan bu issue'yu kapatıyoruz.

https://github.com/Medyasoft/unigate-public/issues/56
