### ISSUE TITLE
Site Map Yeni Sayfa Ekleme Sonucunda Oluşan Durum

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#103]
site mapten root dizine bir sayfa eklemeye kalktığımızda aşağıdaki hatayı almaktayız ; 
404
Recursive write lock acquisitions not allowed in this mode.

Özellikler ; 
Mcms.Sdk  v4.0.30319 
Mcms.UI.Framework  v4.0.30319 

Yeni oluşturulan template seçildi ve Yayında seçeneği ile .

**Comment by tahsinilhan** [comment]
Bu proje de de app Vers : 4.0.0.5

**Comment by esrefatak** [comment]
problem devam ediyor mu?
kontrol ettiğimizde öyle bir problem görmüyoruz?

**Comment by tahsinilhan** [comment]
şuan benim müdahil olduğum projelerde sitemap den sayfa ekleme işlemi
olmuyor ve/veya sorun çıkmıyor .


2015-02-05 14:25 GMT+02:00 esrefatak <notifications@github.com>:

> problem devam ediyor mu?
> kontrol ettiğimizde öyle bir problem görmüyoruz?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/103#issuecomment-73038224>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.
