### ISSUE TITLE
Yeni Oluşturulan Listeye Yeni Kayıt Girilmeye Çalışıldığında oluşan durum

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#104]
Yapılan işlem
Liste oluşturmak 3 adet alan ekleme sonra yani kayıt girme.
Hata Mesajı : Nesne başvurusu bir nesnenin örneğine ayarlanmadı

Mcms.UI.Framework = v4.0.30319
Mcms.Sdk = v4.0.30319

**Comment by esrefatak** [comment]
Application tablosunda yazan ürün versiyonu nedir?

**Comment by tahsinilhan** [comment]
4.0.0.5 versiyonu.

**Comment by esrefatak** [comment]
Veritabanı değişiklik script'lerini uygulayabilir misin?
https://github.com/Medyasoft/unigate-public/wiki/Veritabani-Degisiklik-Scriptleri

**Comment by esrefatak** [comment]
Tahsin selam,

Ürünün son versiyonunda böyle bir problem yok. Yeni versiyona geçebilirsiniz. Eğer problem görürseniz issue'yu tekrar açabilirsiniz.
