### ISSUE TITLE
Listeler arasında ajax ile arama yapılabilmesi

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#105]
unigate listeler bölümünde ; 
liste sayısı arttıkça içlerinden istenileni / aranılanı bulmak zorlaşıyor. 
Bu yüzden bir suggestbox tarzında arama yapılabilinir mi?

**Comment by esrefatak** [comment]
Autosuggest yeterli mi?

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by erturkyilmaz** [comment]
Bence arandıkça alt tarafta liste kısmı yenilenmeli. Ekstra bir alanda
önerilenler çıkmamalı.


*Ertürk Yılmaz*

*Teknik Proje Yöneticisi • Technical Project Manager*
Medyasoft Danışmanlık ve Eğitim A.Ş.
Ord. Prof. Fahrettin Kerim Gökay Caddesi,
Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
*GSM:* 0532 744 61 64 - 0530 415 16 04
erturk.yilmaz@medyasoft.com.tr
www.medyasoft.com.tr



2015-02-03 17:24 GMT+02:00 esrefatak <notifications@github.com>:

> Autosuggest yeterli mi?
>
> --
> YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere
> açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup,
> Şirketimizin
> görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu
> tutulamaz.
>
> DISCLAIMER: The content and the attachments of this e-mail is confidential
> and shall not be disclosed to third parties. Any opinions expressed in
> this
> message are those of the author and may not reflect the opinions of Our
> Company, and Our Company shall not be liable for the content of this
> message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/105#issuecomment-72669120>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by tahsinilhan** [comment]
ertürk e katılıyorum . Anlık filtreleme olmalı yazdıkça liste filtreye göre yüklenmeli.

**Comment by esrefatak** [comment]
Geliştirmeyi yaptık.
Ürünün son versiyona geçerek kullanabilirsiniz.

![image](https://cloud.githubusercontent.com/assets/153772/6059493/d6fe8bee-ad3a-11e4-8684-2af7fdc4555e.png)
