### ISSUE TITLE
Unigate Site Haritası Kayıt Hatası 

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#109]
App Ver: 4.0.0.7 
Mcms.Sdk  : v4.0.30319 

Site Haritasında yeni bir sayfa eklendiğinde ve/veya sayfa editlendiğinde unigate hataya düşüyor. 
ve Unigate in herhangi bir bölümü çalışmıyor hata ekranı gözüküyor . 404 hatası veriyor fakat hata mesajı farklı idi. 
Detay birazdan paylaşıyor olacağım.

**Comment by esrefatak** [comment]
@tahsinilhan  problem yeni versiyonda düzeldiği için konuyu kapatıyoruz

**Comment by tahsinilhan** [comment]
Aynen doğrudur yeni versiyonda bu sorun mevcut degil.

21 Şubat 2015 Cumartesi tarihinde, esrefatak <notifications@github.com>
yazdı:

> @tahsinilhan <https://github.com/tahsinilhan> problem yeni versiyonda
> düzeldiği için konuyu kapatıyoruz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/109#issuecomment-75381796>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by esrefatak** [comment]
@tahsinilhan eyv
