### ISSUE TITLE
UnigateObject ile Update Title zorunluluğu kaldırılması doğru olmaz mı?

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#110]
UnigateObject ile Update işlemi yapılırken , Title alanı boş geçilemez şeklinde hata alınmakta. 
Title alanı insert te zaten zorunlu , update işlemi yapılırken zorunlu olmamalıdır.

**Comment by esrefatak** [comment]
@tahsinilhan  şu anda nasıl yapıyorsunuz tam olarak?

**Comment by tahsinilhan** [comment]
Abi mecbur bir deger giriyoruz . Kullanmadığımız bir alan ise "update
üye/haber -01.01.0001 - şeklinde veya eski degeri çekip yeniden title set
ederek yapıyoruz aksi halde update işlemide hata veriyor.

22 Şubat 2015 Pazar tarihinde, esrefatak <notifications@github.com> yazdı:

> @tahsinilhan <https://github.com/tahsinilhan> şu anda nasıl yapıyorsunuz
> tam olarak?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/110#issuecomment-75433238>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by esrefatak** [comment]
@tahsinilhan bu dediğin düzenlemeyi yaptık. Artık güncellerken title'ı sormuyor. Aynı zamanda EKLERKEN de sormuyor. Yani title ve slug ister insert esnasında ister update esnasında artık sormuyor sistem. Update esnasında;

eğer title veya slug'ı göndermezsen mevcut datayı koruyor güncellemiyor.

insert esnasında;

eğer title veya slug'ı göndermezsen (ki göndermek zorunda değilsin artık) sistem otomatik bir değer atıyor.

**Comment by tahsinilhan** [comment]
Teşekkür ederim.
Elinize emeğinize sağlık.

İyi Çalışmalar.


2 Mart 2015 13:01 tarihinde esrefatak <notifications@github.com> yazdı:

> @tahsinilhan <https://github.com/tahsinilhan> bu dediğin düzenlemeyi
> yaptık. Artık güncellerken title'ı sormuyor. Aynı zamanda EKLERKEN de
> sormuyor. Yani title ve slug ister insert esnasında ister update esnasında
> artık sormuyor sistem. Update esnasında;
>
> eğer title veya slug'ı göndermezsen mevcut datayı koruyor güncellemiyor.
>
> insert esnasında;
>
> eğer title veya slug'ı göndermezsen (ki göndermek zorunda değilsin artık)
> sistem otomatik bir değer atıyor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/110#issuecomment-76693241>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.
