### ISSUE TITLE
IE'de fancybox

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#111]
IE'de (11) içerik düzenleme/ekleme fancybox kapatılamıyor.
Bir içeriği tıkla, Düzenle'ye bas, sonra Onayla'ya bas, fancybox'ı kapatmaya çalış kapanmayacak.

Chrome ve Firefox'ta sorunsuz.

**Comment by esrefatak** [comment]
@serhatozturk  kontrol edebildiniz mi?
Sorun düzelmiş ise kapatıyoruz issue'yu?

**Comment by serhatozturk** [comment]
Erciyas projesinde kontrol edildi, kapatılabilir.

**Comment by esrefatak** [comment]
@serhatozturk teşekkürler, kapatıyorum.

Not: Proje ismi söylemiyoruz burası public bir ortam çünkü
