### ISSUE TITLE
Listenin geçtiği veri kaynaklarını gösteren bir grid

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#112]
Çark simgesi Veri Kaynakları tıklayınca gelen pencerede;

- O listenin kullanıldığı tüm veri kaynakları listelensin: Title,Key,Action,JSON link
- Yeni veri kaynağı generate edildiğinde kullanıcıyı bu gride düşürsün, şu anda veri kaynağı modülüne yönlendiriyor

**Comment by SametDEDE** [comment]
:+1:
