### ISSUE TITLE
Unigate Object ile IN sorgusu

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#119]
Örneğin SQL'de select * from TABLO_ADI where ID in (1,2,3,4) gibi kullanımı UnigateObject ile yapabiliyor olmamız daha iyi olmaz mı ?

**Comment by hguven** [comment]
Geliştirme yapıldı . DataSource tarafından ve unigate object tarafından desteklenecek sekilde geliştirildi.
DataSource Kullanımı:
{ 
  "Lists": [
    {
      "Name": "Page"
    }
  ],
  "Filters": [
    {
      "Column": "Page.Id",
      "Criteria": "IN",
      "Value": "1,2,3"
    }
  ]
}
UnigateObject Kullanımı: 
UnigateObject.Query("TABLO_ADI").WhereIn("Id", new[] {"1","2","3"});
