### ISSUE TITLE
Editör-File Manager bağlantısı

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#132]
- Resim ekleyip sayfaya eklemek için
- Dosya ekleyip link vermek için

**Comment by esrefatak** [comment]
Editör'ün CK Editor'e geçirilmesi gibi bir öneri var. Görüşü olan?

**Comment by erturkyilmaz** [comment]
CK Editör kullanımıyla ilgili zaman zaman chrome'da sorunlar çıktığını
duymuştum..

*Ertürk Yılmaz*

*Teknik Proje Yöneticisi • Technical Project Manager*
Medyasoft Danışmanlık ve Eğitim A.Ş.
Ord. Prof. Fahrettin Kerim Gökay Caddesi,
Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
*GSM:* 0532 744 61 64 - 0530 415 16 04
erturk.yilmaz@medyasoft.com.tr
www.medyasoft.com.tr



2015-03-03 17:38 GMT+02:00 esrefatak <notifications@github.com>:

> Editör'ün CK Editor'e geçirilmesi gibi bir öneri var. Görüşü olan?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/132#issuecomment-76968864>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by esrefatak** [comment]
Net bir bulgu var mı? Söylentiler üzerinden karar vermek zaman efor
kaybettirebilir.

>

-- 
Eşref Atak

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by erturkyilmaz** [comment]
Linkleri kontrol edebilirsiniz.

http://forum.donanimhaber.com/m_84089745/tm.htm
http://ckeditor.com/forums/CKEditor-3.x/Problem-Chrome
https://www.drupal.org/node/1371554

*Ertürk Yılmaz*

*Teknik Proje Yöneticisi • Technical Project Manager*
Medyasoft Danışmanlık ve Eğitim A.Ş.
Ord. Prof. Fahrettin Kerim Gökay Caddesi,
Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
*GSM:* 0532 744 61 64 - 0530 415 16 04
erturk.yilmaz@medyasoft.com.tr
www.medyasoft.com.tr



2015-03-03 19:45 GMT+02:00 esrefatak <notifications@github.com>:

> Net bir bulgu var mı? Söylentiler üzerinden karar vermek zaman efor
> kaybettirebilir.
>
> >
>
> --
> Eşref Atak
>
> --
> YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere
> açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup,
> Şirketimizin
> görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu
> tutulamaz.
>
> DISCLAIMER: The content and the attachments of this e-mail is confidential
> and shall not be disclosed to third parties. Any opinions expressed in
> this
> message are those of the author and may not reflect the opinions of Our
> Company, and Our Company shall not be liable for the content of this
> message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/132#issuecomment-76995739>
> .
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by erturkyilmaz** [comment]
Şuan böyle bir sorun var mı bilmiyorum, aklımda kaldığı için paylaşmak
istedim.

*Ertürk Yılmaz*

*Teknik Proje Yöneticisi • Technical Project Manager*
Medyasoft Danışmanlık ve Eğitim A.Ş.
Ord. Prof. Fahrettin Kerim Gökay Caddesi,
Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
*GSM:* 0532 744 61 64 - 0530 415 16 04
erturk.yilmaz@medyasoft.com.tr
www.medyasoft.com.tr



3 Mart 2015 20:00 tarihinde Ertürk Yılmaz <erturk.yilmaz@medyasoft.com.tr>
yazdı:

> Linkleri kontrol edebilirsiniz.
>
> http://forum.donanimhaber.com/m_84089745/tm.htm
> http://ckeditor.com/forums/CKEditor-3.x/Problem-Chrome
> https://www.drupal.org/node/1371554
>
> *Ertürk Yılmaz*
>
> *Teknik Proje Yöneticisi • Technical Project Manager*
> Medyasoft Danışmanlık ve Eğitim A.Ş.
> Ord. Prof. Fahrettin Kerim Gökay Caddesi,
> Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
> *GSM:* 0532 744 61 64 - 0530 415 16 04
> erturk.yilmaz@medyasoft.com.tr
> www.medyasoft.com.tr
>
>
>
> 2015-03-03 19:45 GMT+02:00 esrefatak <notifications@github.com>:
>
>> Net bir bulgu var mı? Söylentiler üzerinden karar vermek zaman efor
>> kaybettirebilir.
>>
>> >
>>
>> --
>> Eşref Atak
>>
>> --
>> YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere
>> açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup,
>> Şirketimizin
>> görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu
>> tutulamaz.
>>
>> DISCLAIMER: The content and the attachments of this e-mail is
>> confidential
>> and shall not be disclosed to third parties. Any opinions expressed in
>> this
>> message are those of the author and may not reflect the opinions of Our
>> Company, and Our Company shall not be liable for the content of this
>> message.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Medyasoft/unigate-public/issues/132#issuecomment-76995739>
>> .
>>
>
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by emrahtokalak** [comment]
TinyMCE vs CK , bence ikisininde artı yönleri var ama CK kral.

Tavsiyem Orchard gibi bunların plugin olarak tanımlanması ve istenilenin sistemde aktif olmasından yana. Çok daha profosyonel ve + özellik olur. 

İleride MarkDown editörde koyarsın, xyz editör desteğinide bu şekilde verirsin. Maksat modül olsun.

Sevgiler.

**Comment by esrefatak** [comment]
@emrahtokalak  Bu çok doğru bir yaklaşım, haklısın; plugin şeklinde olmalı.
