### ISSUE TITLE
Listelerde Action sütununda Copy ContentId butonu

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#138]
Örneğin Member'ın ContentId'si gerektiğinde URL'e gidip kopyalamak gerekiyor. Bu buton eklenirse, hızlıca ContentId alınabilir.
![screen shot 2015-03-03 at 09 50 04](https://cloud.githubusercontent.com/assets/2884854/6458296/b26f2c52-c18a-11e4-998b-2a17096ed2a1.png)

**Comment by esrefatak** [comment]
Orası son kullanıcıların da kullandığı çok göz önünde bir yer. Onu içerik detay ekranında göstermek daha uygun. Oraya ekleyeceğiz.

**Comment by esrefatak** [comment]
Artık ID görülebiliyor, içeriğin içinden:

![image](https://cloud.githubusercontent.com/assets/153772/6998206/2dbaace0-dbe1-11e4-8eb3-90afbd927b16.png)
