### ISSUE TITLE
Listeye kayıt eklendiğinde yeniden bir kayıt daha seri şekilde girilebilsin

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#141]
Listeye unigate tarafından bir kayıt girildiğinde , işlem sonucu bilgisi verilsin ve başarılı ise alanlar temizlensin yeni kayıt girmeye müsade etsin . 
İyi olmaz mı ? 
Aksi halde ; 
işlem başarılı ise fancybox (yada lightbox :)  ) kapatılıp yeniden ekle butonu cliklenip yeniden kayıt giriliyor. 

Seri birşekilde veri girişinde ciddi zaman ve performans kaybı olabilir.

**Comment by esrefatak** [comment]
Onaylama düğmesi dropbox'lı hale getirilecek. Seçenekler:

- Onayla (default)
- Onayla ve Yeni Ekle
- Onayla ve Kapat
