### ISSUE TITLE
Dosya Kaydetme Problemi

### ISSUE THREAD

**Issue by serhatozturk** [Medyasoft/unigate-public#155]
UnigateObject ile dosya tipindeki bir alana yeni kayıt atılmaya veya mevcut kayıt değiştirilmeye kalktığında, alana veriyi kaydetmiyor ve mevcut kayıdı da empty yapıyor.

Şu anda işlemlerin aksamaması amacıyla Dosya tipindeki alanı tipini ADO ile Tekk Satırlı Metin yapıp kayıt işlemini gerçekleştiriyor ve ardından tekrar tipini Dosya yapıyoruz.

Aslında bu özelliğin düzeltilmesi ile birlikte dosyanın path'e kaydedilmesi ve bu sırada dosya adının içeriğe göre düzenlenmesi işlemlerininde Unigate tarafından sunulacak bir fonksiyon ile yapılmasında fayda olduğunu düşünüyorum.

**Comment by hguven** [comment]
serhat unigateobject ile dosya güncelleme yapabilmeniz için bir fonksiyonunuz var mı. Update yaptığın kodu buraya yapıştırabilir misin ?

**Comment by serhatozturk** [comment]
@hguven bu zamana kadar dosyayı güncellediğimiz bir işlem yapmadık. Sadece Title veya OrderNo gibi alanları güncelledik.

**Comment by hguven** [comment]
24.04.2015 itibari ile fix edildi. Kapatıyorum
