### ISSUE TITLE
Listeye yeni sütun eklerken Tamam ve Vazgeç butonları gözükmüyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#156]
Mac Chrome için;

Listede Sütunlara gelip + ikonuna tıkladığımda açılan popupta Tamam ve Vazgeç butonları yok. Popup'ı kapatıp tekrar + ya bastığımda geliyor. 

Sadece ilk açtığında gözükmüyor.

**Comment by SametDEDE** [comment]
Sütun ekledikten sonra yine ilk açtığımda görünmüyor.

**Comment by esrefatak** [comment]
Bu problem düzeltildi. Son versiyonu aldığınızda düzelir.

-- 
Eşref Atak
Unigate Ürün Müdürü (www.unigate.com.tr)
Medyasoft (www.medyasoft.com.tr)

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.
