### ISSUE TITLE
Unigate Object Update Hatası

### ISSUE THREAD

**Issue by hguven** [Medyasoft/unigate-public#164]
Liste olmayan bir tabloda koşulsuz update yapmak istenildiği zaman işlem gerçekleştiremiyor

UnigateObject.Update("Table").Column("Column", DateTime.Now).Execute();

**Comment by hguven** [comment]
Bug giderildi. Insert ederken

```
UnigateObject.Update("Table").Column("Column", DateTime.Now.ToString("yyyy-mm-dd hh:mm:dd").Execute();
```


şeklinde insert edilmesi gerekiyor

**Comment by esrefatak** [comment]
Update komutu ile mi insert ediyoruz?

Normal insert komutundan farklı bir komut vermiyorum değil mi?



-- 
Eşref Atak
Unigate Ürün Müdürü (www.unigate.com.tr)
Medyasoft (www.medyasoft.com.tr)

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.
