### ISSUE TITLE
Eklenti ekleme problemi

### ISSUE THREAD

**Issue by AyhanISIK** [Medyasoft/unigate-public#167]
4.2.0.0 versiyonu ile birlikte eklenti ekleme fonksiyonu çalışmamaktadır. Sağ altta ki managementmenu'de hiç bir buton işlem yapmıyor.

**Comment by esrefatak** [comment]
``````
/areas/unigate/static/v1/js/ui.js
/areas/unigate/static/v1/css/ui.css
``````

Bu iki dosya var mı projende?

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by esrefatak** [comment]
<head>
        @Html.FrontHtml().RenderManagementHeader()
        ...
    </head>
    <body>
        ...
        @Html.FrontHtml().RenderManagementMenu()
    </body>

Bu iki satır var mı template'lerinizde?

**Comment by AyhanISIK** [comment]
Dosyalar mevcuttu. Header'da ki alan eksikti, ekledik çalışıyor. Diğer projelerde de bu alanları eklemek gerekecek.
