### ISSUE TITLE
Belirtilen sütun tipinin doğru şekilde gelmemesi.

### ISSUE THREAD

**Issue by AyhanISIK** [Medyasoft/unigate-public#168]
“İçerik” sütunu Uzun HTML tipinde olmasına rağmen , mevcut bir içeriği açtığımda Textarea gözükmektedir. Ancak Yeni İçerik eklemeye kalktığımda CKEditr görünmektedir. Test amacıyla gidip “İçerik” sütununun tipini önce “Çok Satırlı Metin”, ardından tekrar “Uzun HTML” yapmama rağmen düzelmemektedir.

**Comment by esrefatak** [comment]
Gizli olan bir sütundan kaynaklı bug. Gizli sütunu gösterip tekrar deneyebilir misin?

Üründeki bir bug. Düzeltildiğinde bu issue'yu kapatıyor olacağız.

**Comment by serhatozturk** [comment]
Gizli sütundan daha çok bir sütuna Sıra no verilmemesinden kaynaklanıyor olabilir. Çünkü sıra nosuz sütuna sıra no verince problem ortadan kalktı.

**Comment by esrefatak** [comment]
Sıra no şans eseri düzeltmiş anlaşılan. Konu gizli sütunlarla ilgiliydi test ettik. Sıra no değiştirdiğinizde js console'da geteditor şeklinde bir js hatası görüyor musunuz?
