### ISSUE TITLE
Admin pluginlerine rol atama problemi

### ISSUE THREAD

**Issue by AyhanISIK** [Medyasoft/unigate-public#169]
Admin plugin'lerine Admin yetkisi dışında herhangi bir rolle erişim sağlanamıyor.

**Comment by esrefatak** [comment]
plugin.json dosyasında rolleri yazdınız mı?

**Comment by esrefatak** [comment]
Kontrol ettiniz mi?

**Comment by serhatozturk** [comment]
Kadıköy projelerinde kontrol ettik, Editor rolü yazıyoruz ancak plugin menüde görünmesine rağmen tıkladığımızda  Access Denied hatası veriyor.

**Comment by hguven** [comment]
Tamamlandı test edip kapatılacak. Yeni patch ile düzeltme gelecek
