### ISSUE TITLE
Yeni bir plugin property tipi: Content

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#177]
Kullanıcıya "İçeriği Seçiniz" diyecek.
Önce listeyi seçecek sonra içindeki içeriği seçecek. İçerik listeleme ajax ile filtrelenmeli çok içerik olabilir çünkü.

**Comment by erturkyilmaz** [comment]
İçeriğin hangi listede olduğu o an hatırlanmıyorsa ne yapılacak? Öngörünüz
böyle bir duruma çok az rastlanacağı şeklinde mi?

*Ertürk Yılmaz*

*Teknik Proje Yöneticisi • Technical Project Manager*
Medyasoft Danışmanlık ve Eğitim A.Ş.
Ord. Prof. Fahrettin Kerim Gökay Caddesi,
Eşref Çakmak Plaza No:32 Kat 2, 34662, Altunizade, Üsküdar/İstanbul
*GSM:* 0532 744 61 64 - 0530 415 16 04
erturk.yilmaz@medyasoft.com.tr
www.medyasoft.com.tr



7 Mayıs 2015 09:58 tarihinde esrefatak <notifications@github.com> yazdı:

> Kullanıcıya "İçeriği Seçiniz" diyecek.
> Önce listeyi seçecek sonra içindeki içeriği seçecek. İçerik listeleme ajax
> ile filtrelenmeli çok içerik olabilir çünkü.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medyasoft/unigate-public/issues/177>.
>

-- 
YASAL UYARI: Bu e-postanın içeriği ve ekleri gizlidir ve üçüncü kişilere 
açıklanamaz. Bu e-postada yer alan görüşler yazarına ait olup, Şirketimizin 
görüşlerini yansıtmayabilir ve mesajın içeriğinden Şirketimiz sorumlu 
tutulamaz. 

DISCLAIMER: The content and the attachments of this e-mail is confidential 
and shall not be disclosed to third parties. Any opinions expressed in this 
message are those of the author and may not reflect the opinions of Our 
Company, and Our Company shall not be liable for the content of this 
message.

**Comment by esrefatak** [comment]
Şimdilik liste seçme şeklinde ilerlemeyi planlıyoruz. İçeriğin nerede olduğunu hatırlamıyorsa durumu için genel bir arama aracı yapmak işi çözer mi ne düşünüyorsun? Örneğin "başkan geldi" diye yazdığında tüm listelerde arasa ekrana dökse hangi listede geçtiğini de görse tıklayıp seçse?

**Comment by erturkyilmaz** [comment]
Genel bir arama aracı kesinlikle işi çözer. 

Kullanıcıya "İçeriği giriniz" diyoruz.
Direkt tüm listelerde arama yapılarak uygun listeler anında filtreleniyor ve editörlerin hayatı kolaylaşmış oluyor.

Bu istek daha önceden yazmış olduğum #173 maddesiyle bire-bir örtüşüyor.

**Comment by esrefatak** [comment]
O madde de kalsın bence. Onun amacı farklı. Onu da yapmak lazım.
