### ISSUE TITLE
Unigate panelde sol menüde customization yapabilme

### ISSUE THREAD

**Issue by erturkyilmaz** [Medyasoft/unigate-public#183]
Mesajlaşma menüsünde yeni bir mesaj geldiğinde text'in yanına rakam yazıp yeni kaç mesaj geldiğini gösterebilmeliyiz. (Üst menüde notification göstermenin haricinde bir istek)

**Comment by esrefatak** [comment]
Biraz daha açar mısın bunu? Örnek bir case mesela?

**Comment by erturkyilmaz** [comment]
Mesajlaşma ve Duyurular için iki ayrı plugin yazdığımızı düşünelim. 
Sol menüde ikisinide ayrı ayrı gösteriyor olmalıyız tıpkı aşağıdaki gibi.

![ekran alintisi1](https://cloud.githubusercontent.com/assets/7019509/7628282/1cd6e666-fa2a-11e4-91ab-a009b64d8ff3.JPG)

Ve ben iki ayrı plugin'de kullanıcıya yeni bir mesaj / duyuru geldiğinde ayrı ayrı bildirmek istiyor olabilirim.

Yeni gelen mesaj sayıları, yeni gelen duyuru sayıları vb. gibi.

Bu durumda aşağıdaki gibi bir bildirim yapmak isterim.

![ekran alintisi2](https://cloud.githubusercontent.com/assets/7019509/7628314/82a0352e-fa2a-11e4-8053-78e1e4bfab19.JPG)

Bunu şuan yapabiliyor muyuz bilmiyorum açıkçası.

**Comment by esrefatak** [comment]
Evet şu anda mümkün değil, feature req olarak işaretliyorum
