### ISSUE TITLE
CKEditor video ve resim ekleme sorunu

### ISSUE THREAD

**Issue by AyhanISIK** [Medyasoft/unigate-public#184]
CKEditor'den video eklemek için video klasörüne gelindiğinde dosyalar görünmüyor. Aynı sorun resim ekleme işleminde de mevcut.

**Comment by esrefatak** [comment]
@yilmazbuhar CK'ün bir dosyasından bu ayarlanabiliyordu sanırım?

**Comment by yilmazbuhar** [comment]
Eklemek veya görüntülemek istediğiniz dosya formatlarını 4.2.1 versiyondan itibaren setting.json dosyasından ayarlamanız gerekiyor. Resim ekleme ile ilgili sorunlar da bu versiyon ile çözülmüştü.Devam eden sorunlar varsa detaylandırabilirsiniz.
