### ISSUE TITLE
Editable plugin - edit moddayken HTML ekrana basılıyor

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#192]
Ziyaretçilere ise düzgün görünüyor:

![image](https://cloud.githubusercontent.com/assets/153772/7703924/bcccef22-fe43-11e4-8ecf-65a905d8224f.png)

**Comment by yilmazbuhar** [comment]
Html.Raw(Editable("Test","text",true,"Varsayılan değer")) şekilde çözebilirsin.
