### ISSUE TITLE
FieldKey ve FieldValue isimleri

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#203]
Aşağıdaki şekilde kullanalım:

FieldKey --> Title
FieldValue --> Value

...kullanalım. Yani plugini sitesine ekleyen bir kişi normal bir liste oluşturduktan sonra yalnızca PageId ve Value sütunlarını ekleyecek.

**Comment by yilmazbuhar** [comment]
FieldValue => Value olarak değiştirildi
FieldKey => FieldKey olarak kaldı.
