### ISSUE TITLE
bin'e erişilemedi hata mesajı

### ISSUE THREAD

**Issue by esrefatak** [Medyasoft/unigate-public#204]
Editable plugin'in bir cshtml'inde düzenleme yapınca ortaya çıktı. Defalarda kez yaptım sorun çıkmadı bir anda oldu.

/unigate 'e geçip tekrar dönünce düzeldi herşey normale döndü.

![image](https://cloud.githubusercontent.com/assets/153772/7917095/7b2b6146-0890-11e5-9e00-c528a0efa10b.png)

**Comment by hguven** [comment]
Rebuild yaparsan düzelir aslında

1 Haz 2015 Pzt, 19:02 tarihinde, esrefatak <notifications@github.com> şunu
yazdı:

**Comment by esrefatak** [comment]
Doğrudan canlı sitede yaşandı durum. Local'de geliştirme esnasında değil.
