### ISSUE TITLE
Listelerde satır yüksekliği standarttan fazla ise tüm kayıtlar gösterilemiyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#30]
Örnek : Çok Satırlı Metin ya da Görsel içeren bir listede 10 kayıt ekleyin, 7-8 tanesi görünüyor. Devamı scroll sonunda kalıyor, gösterilemiyor.

**Comment by esrefatak** [comment]
@hguven  @SametDEDE 

Infinitive scroll'u kaldırınca düzelecek gibi görünüyor. Birlikte test eder misiniz yeni halini gördükten sonra?
