### ISSUE TITLE
Web servislerde uniqueIdentifier alanlara NULL gönderilebiliyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#44]
NULL kayıt olduğunda liste içeriği görüntülenemiyor

**Comment by SametDEDE** [comment]
Düşündüğümüz çözümler;

- Gelen boş string ise NULL olarak yazılacak
ya da
- Relation ekleyebilmek için listede ilgili column baştan uniqueIdentifier olarak seçilmesi zorunlu hale getirilecek. Relation ekleme ekranında sadece uniqueIdentifier tipindeki columnlar gösterilecek.

**Comment by esrefatak** [comment]
Son düzenlemeler ile bu konu da hallolmuş durumda.

relation olan alanlara NULL kaydedilebiliyor olması problem değil. "" gönderilince "" kaydediyordu bu düzeltildi, artık "" gönderince NULL kaydediyor sistem otomatik olarak.
