### ISSUE TITLE
Nested JSON yapısı

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#51]
Joinli listelerden gelen veriler birleştirilip tek bir web servisten alınabilse?

Örneğin GetSeries servisinden şöyle bir dönüş alabilsek?

```
Diziler: [
   Dizi: {
      Bölümler: [
         Bölüm : {
            ...
         },...
      ], Fragmanlar: [
          ...
      ], ...
   }, Dizi: {
      Bölümler: [
         Bölüm : {
            ...
         },...
      ], Fragmanlar: [
          ...
      ], ...
   },...
]
```

**Comment by esrefatak** [comment]
Bu özellik verikaynaklarına ekleyeceğimiz bir özellik değil maalesef. Diğer projede olduğu gibi webapi geliştirme ile sağlanması daha uygun olacaktır. Konuyu kapatıyorum.
