### ISSUE TITLE
Bir kaydı sildiğimde, içindeki dosyalar dosya sisteminde kalıyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#55]

**Comment by esrefatak** [comment]
https://github.com/Medyasoft/unigate-public/issues/68 issue'suna alt madde olarak ekliyorum ayrı bir issue olarak takip edilmesi yerine diğerinde takip edilmesi daha verimli olacak

**Comment by esrefatak** [comment]
Dosyaları silmemiz doğru olmaz. Kaydı geri getirme özelliği katacağız yakında. O zaman dosyaları kaybetmiş oluruz. Dosyaların da geri gelmesi için kalması lazım dosyaların.
