### ISSUE TITLE
Kaydı silme butonuna bastığımda, detay popup'ı açılıyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#56]
Çöp kutusu ikonuna bastım. İçerik silinecek. Emin misiniz? alert'ı geldi, bir yandan da popup açıldı. 

Kaydı sildim, popupdan düzenle deyip kaydettim. Yeni kayıt olarak tekrar ekledi.

**Comment by esrefatak** [comment]
@vunalan

**Comment by SametDEDE** [comment]
:+1:
