### ISSUE TITLE
Veri kaynaklarını GetGallery?GalleryId=4 yerine GetGallery/4 şeklinde çağırmak

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#59]
mümkün mü?

**Comment by esrefatak** [comment]
Mükerrer olduğu için issue'yu kapatıyoruz. Diğerinin altına ek feature olarak ekliyoruz.

Veri kaynaklarını GetGallery?GalleryId=4 yerine GetGallery/4 şeklinde çağırmak
