### ISSUE TITLE
Liste ayarlarında önceki listenin sütun bilgileri geliyor

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#66]
Bir listeye girip sütunlarında değişiklik yapıp kaydediyorum. Başka bir listeye geçip sütun ayarlarına girdiğimde bir önceki listenin sütun bilgileri geliyor.

**Comment by esrefatak** [comment]
Mükerrer

https://github.com/Medyasoft/unigate-public/issues/18
