### ISSUE TITLE
İçeriklerde devam eden düzenlemeleri görme imkanı

### ISSUE THREAD

**Issue by SametDEDE** [Medyasoft/unigate-public#67]
Çok kullanıcılı bir sistemde bir kullanıcı kaydı açıp kaydet ya da onayla demeden bırakabiliyor. Çok fazla kayıt olduğundan bu açık kayıtları tek tek bakıp hangisinin açık kaldığını bulmak mümkün olmayabiliyor.

- [ ] Hangi içerikte çalışma var görebilelim
- [ ] Üzerinde çalışan kim görebilelim

**Comment by esrefatak** [comment]
Bu konuda geliştirme yaptık. issue'yu kapatıyoruz. Yeni halini kontrol edip eksik varsa yeni bir issue ekleyebilirsin.

@SametDEDE
