### ISSUE TITLE
Liste silinebilmesi

### ISSUE THREAD

**Issue by tahsinilhan** [Medyasoft/unigate-public#91]
yanlışlıkla açılmış bir liste veya açılmış fakat işlevini yitirmiş / iptal olmuş / kullanılmayan bir liste nin silinebilmesi imkanı olabilir mi?

**Comment by esrefatak** [comment]
Mükerrer olduğu için siliyoruz issue'yu

https://github.com/Medyasoft/unigate-public/issues/37
